from __future__ import annotations

import json
import os
import re
import sys
from pathlib import Path
from typing import Any

import numpy as np
import pandas as pd

from radiogenpdac.preprocessing import (
    center_from_mask,
    clip_and_scale,
    crop_centered,
    default_center,
    resolve_phase_path,
)


def _is_missing(value: Any) -> bool:
    return value is None or (isinstance(value, float) and np.isnan(value)) or str(value).strip() == ""


def _sanitize_case_id(value: str, index: int) -> str:
    sanitized = re.sub(r"[^A-Za-z0-9]+", "_", value).strip("_")
    if not sanitized:
        sanitized = f"case_{index:04d}"
    return sanitized


def _bootstrap_pdac_detection(
    pdac_root: str | Path,
    nnunet_raw_dir: str | Path | None = None,
    nnunet_preprocessed_dir: str | Path | None = None,
    nnunet_results_dir: str | Path | None = None,
) -> Path:
    root = Path(pdac_root).expanduser().resolve()
    package_paths = [
        root / "packages" / "nnunetv2",
        root / "packages" / "report-guided-annotation",
    ]
    for package_path in package_paths:
        package_path_str = str(package_path)
        if package_path.exists() and package_path_str not in sys.path:
            sys.path.insert(0, package_path_str)

    if nnunet_raw_dir is not None:
        os.environ["nnUNet_raw"] = str(Path(nnunet_raw_dir).expanduser().resolve())
    if nnunet_preprocessed_dir is not None:
        os.environ["nnUNet_preprocessed"] = str(Path(nnunet_preprocessed_dir).expanduser().resolve())
    if nnunet_results_dir is not None:
        os.environ["nnUNet_results"] = str(Path(nnunet_results_dir).expanduser().resolve())
    return root


def _write_dataset_json(
    dataset_dir: Path,
    dataset_name: str,
    num_training_cases: int,
) -> None:
    payload = {
        "channel_names": {"0": "CT"},
        "labels": {"background": 0, "tumor": 1},
        "numTraining": int(num_training_cases),
        "file_ending": ".nii.gz",
        "name": dataset_name,
        "description": "Phase-specific PDAC tumor fine-tuning dataset generated by RadiogenPDAC.",
    }
    (dataset_dir / "dataset.json").write_text(json.dumps(payload, indent=2), encoding="utf-8")


def _write_nifti(source: str | Path, destination: Path, is_label: bool) -> None:
    try:
        import SimpleITK as sitk
    except ImportError as exc:  # pragma: no cover - optional dependency
        raise RuntimeError("SimpleITK is required for the PDAC encoder pipeline") from exc

    image = sitk.ReadImage(str(source))
    if is_label:
        array = sitk.GetArrayFromImage(image)
        binary = (array > 0).astype(np.uint8)
        image = sitk.GetImageFromArray(binary)
        image.CopyInformation(sitk.ReadImage(str(source)))
    else:
        image = sitk.Cast(image, sitk.sitkFloat32)
    sitk.WriteImage(image, str(destination), useCompression=True)


def prepare_phase_finetune_dataset(
    manifest_path: str | Path,
    phase: str,
    dataset_id: int,
    dataset_name: str,
    pdac_root: str | Path,
    nnunet_raw_dir: str | Path,
    output_index_path: str | Path | None = None,
) -> pd.DataFrame:
    _bootstrap_pdac_detection(pdac_root=pdac_root, nnunet_raw_dir=nnunet_raw_dir)

    frame = pd.read_csv(manifest_path)
    dataset_dir = Path(nnunet_raw_dir).expanduser().resolve() / f"Dataset{dataset_id:03d}_{dataset_name}"
    images_dir = dataset_dir / "imagesTr"
    labels_dir = dataset_dir / "labelsTr"
    images_dir.mkdir(parents=True, exist_ok=True)
    labels_dir.mkdir(parents=True, exist_ok=True)

    rows: list[dict[str, Any]] = []
    used_case_ids: set[str] = set()
    for index, row in frame.iterrows():
        patient_id = str(row["patient_id"])
        image_path = resolve_phase_path(row, phase, "image")
        mask_path = resolve_phase_path(row, phase, "tumor_mask", fallback_columns=["tumor_mask"])
        if _is_missing(image_path) or _is_missing(mask_path):
            continue

        case_id = _sanitize_case_id(patient_id, index)
        while case_id in used_case_ids:
            case_id = f"{case_id}_{index:04d}"
        used_case_ids.add(case_id)

        image_dest = images_dir / f"{case_id}_0000.nii.gz"
        label_dest = labels_dir / f"{case_id}.nii.gz"
        _write_nifti(str(image_path), image_dest, is_label=False)
        _write_nifti(str(mask_path), label_dest, is_label=True)
        rows.append(
            {
                "patient_id": patient_id,
                "phase": phase,
                "case_id": case_id,
                "image_path": str(image_dest),
                "label_path": str(label_dest),
            }
        )

    _write_dataset_json(dataset_dir=dataset_dir, dataset_name=dataset_name, num_training_cases=len(rows))
    index_path = (
        Path(output_index_path).expanduser().resolve()
        if output_index_path is not None
        else dataset_dir / f"{phase}_training_index.csv"
    )
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_frame = pd.DataFrame(rows)
    index_frame.to_csv(index_path, index=False)
    return index_frame


def plan_and_preprocess_phase_dataset(
    dataset_id: int,
    pdac_root: str | Path,
    nnunet_raw_dir: str | Path,
    nnunet_preprocessed_dir: str | Path,
    nnunet_results_dir: str | Path,
    plans_identifier: str,
    configurations: list[str],
    gpu_memory_target_gb: float = 8.0,
    num_processes: int = 4,
    verify_integrity: bool = False,
    overwrite_target_spacing: list[float] | None = None,
) -> None:
    _bootstrap_pdac_detection(
        pdac_root=pdac_root,
        nnunet_raw_dir=nnunet_raw_dir,
        nnunet_preprocessed_dir=nnunet_preprocessed_dir,
        nnunet_results_dir=nnunet_results_dir,
    )

    from nnunetv2.experiment_planning.plan_and_preprocess_api import (
        extract_fingerprint_dataset,
        plan_experiment_dataset,
        preprocess_dataset,
    )

    extract_fingerprint_dataset(
        dataset_id=dataset_id,
        num_processes=num_processes,
        check_dataset_integrity=verify_integrity,
    )
    plan_experiment_dataset(
        dataset_id=dataset_id,
        gpu_memory_target_in_gb=gpu_memory_target_gb,
        overwrite_target_spacing=tuple(overwrite_target_spacing) if overwrite_target_spacing else None,
        overwrite_plans_name=plans_identifier,
    )
    preprocess_dataset(
        dataset_id=dataset_id,
        plans_identifier=plans_identifier,
        configurations=configurations,
        num_processes=[num_processes] * len(configurations),
    )


def finetune_phase_encoder(
    dataset_id: int,
    pdac_root: str | Path,
    nnunet_raw_dir: str | Path,
    nnunet_preprocessed_dir: str | Path,
    nnunet_results_dir: str | Path,
    configuration: str,
    fold: int,
    trainer_name: str,
    plans_identifier: str,
    pretrained_weights: str | Path,
    device: str = "cuda",
    num_gpus: int = 1,
    export_validation_probabilities: bool = False,
    continue_training: bool = False,
    only_run_validation: bool = False,
) -> Path:
    _bootstrap_pdac_detection(
        pdac_root=pdac_root,
        nnunet_raw_dir=nnunet_raw_dir,
        nnunet_preprocessed_dir=nnunet_preprocessed_dir,
        nnunet_results_dir=nnunet_results_dir,
    )

    import torch
    from nnunetv2.run.run_training import run_training
    from nnunetv2.utilities.dataset_name_id_conversion import convert_id_to_dataset_name

    dataset_name = convert_id_to_dataset_name(dataset_id)
    run_training(
        dataset_name_or_id=dataset_name,
        configuration=configuration,
        fold=fold,
        trainer_class_name=trainer_name,
        plans_identifier=plans_identifier,
        pretrained_weights=str(Path(pretrained_weights).expanduser().resolve()),
        num_gpus=num_gpus,
        export_validation_probabilities=export_validation_probabilities,
        continue_training=continue_training,
        only_run_validation=only_run_validation,
        device=torch.device(device),
    )

    return (
        Path(nnunet_results_dir).expanduser().resolve()
        / dataset_name
        / f"{trainer_name}__{plans_identifier}__{configuration}"
    )


def _resample_to_reference(mask: Any, image: Any) -> Any:
    import SimpleITK as sitk

    if (
        mask.GetSize() == image.GetSize()
        and mask.GetSpacing() == image.GetSpacing()
        and mask.GetOrigin() == image.GetOrigin()
        and mask.GetDirection() == image.GetDirection()
    ):
        return mask
    return sitk.Resample(mask, image, sitk.Transform(), sitk.sitkNearestNeighbor, 0, sitk.sitkUInt8)


def _crop_image_and_mask(image: Any, mask: Any, margin_mm: list[float]) -> tuple[Any, Any]:
    import SimpleITK as sitk

    mask = _resample_to_reference(mask, image)
    mask_array = sitk.GetArrayFromImage(mask)
    coordinates = np.argwhere(mask_array > 0)
    if coordinates.size == 0:
        raise ValueError("Tumor mask is empty")

    min_zyx = coordinates.min(axis=0)
    max_zyx = coordinates.max(axis=0)
    spacing_xyz = image.GetSpacing()
    margin_xyz = [max(0, int(round(margin_mm[idx] / spacing_xyz[idx]))) for idx in range(3)]

    x_start = max(0, int(min_zyx[2]) - margin_xyz[0])
    x_stop = min(image.GetSize()[0], int(max_zyx[2]) + margin_xyz[0] + 1)
    y_start = max(0, int(min_zyx[1]) - margin_xyz[1])
    y_stop = min(image.GetSize()[1], int(max_zyx[1]) + margin_xyz[1] + 1)
    z_start = max(0, int(min_zyx[0]) - margin_xyz[2])
    z_stop = min(image.GetSize()[2], int(max_zyx[0]) + margin_xyz[2] + 1)
    return (
        image[x_start:x_stop, y_start:y_stop, z_start:z_stop],
        mask[x_start:x_stop, y_start:y_stop, z_start:z_stop],
    )


def _resample_image(image: Any, output_spacing_xyz: tuple[float, float, float], is_label: bool) -> Any:
    import SimpleITK as sitk

    input_spacing = image.GetSpacing()
    input_size = image.GetSize()
    output_size = [
        max(1, int(round(input_size[idx] * (input_spacing[idx] / output_spacing_xyz[idx]))))
        for idx in range(3)
    ]

    resampler = sitk.ResampleImageFilter()
    resampler.SetOutputSpacing(output_spacing_xyz)
    resampler.SetSize(output_size)
    resampler.SetOutputDirection(image.GetDirection())
    resampler.SetOutputOrigin(image.GetOrigin())
    resampler.SetTransform(sitk.Transform())
    resampler.SetDefaultPixelValue(0.0)
    resampler.SetInterpolator(sitk.sitkNearestNeighbor if is_label else sitk.sitkBSpline)
    return resampler.Execute(image)


def _extract_deepest_feature_map(network: Any, inputs: Any) -> Any:
    if hasattr(network, "encoder") and callable(network.encoder):
        encoded = network.encoder(inputs)
        if isinstance(encoded, (list, tuple)):
            for item in reversed(encoded):
                if hasattr(item, "shape"):
                    return item
        if hasattr(encoded, "shape"):
            return encoded
    raise RuntimeError(
        "Unable to access the encoder feature map from the fine-tuned PDAC_Detection network. "
        "This wrapper currently expects a ResidualEncoderUNet-style encoder."
    )


def _masked_average_pool(feature_map: Any, mask: Any) -> Any:
    import torch

    weighted = feature_map * mask
    denominator = mask.sum(dim=(2, 3, 4), keepdim=False).clamp_min(1.0)
    return weighted.sum(dim=(2, 3, 4), keepdim=False) / denominator


def extract_phase_encoder_features(
    manifest_path: str | Path,
    phase: str,
    pdac_root: str | Path,
    nnunet_raw_dir: str | Path,
    nnunet_preprocessed_dir: str | Path,
    nnunet_results_dir: str | Path,
    model_training_output_dir: str | Path,
    fold: int,
    output_dir: str | Path,
    output_manifest: str | Path,
    checkpoint_name: str = "checkpoint_final.pth",
    device: str = "cuda",
    intensity_window_hu: list[float] | None = None,
    margin_mm: list[float] | None = None,
) -> pd.DataFrame:
    _bootstrap_pdac_detection(
        pdac_root=pdac_root,
        nnunet_raw_dir=nnunet_raw_dir,
        nnunet_preprocessed_dir=nnunet_preprocessed_dir,
        nnunet_results_dir=nnunet_results_dir,
    )

    try:
        import SimpleITK as sitk
        import torch
        import torch.nn.functional as F
    except ImportError as exc:  # pragma: no cover - optional dependency
        raise RuntimeError("Feature extraction requires train extras: torch and SimpleITK") from exc

    from nnunetv2.inference.predict_from_raw_data import nnUNetPredictor

    output_root = Path(output_dir).expanduser().resolve()
    output_root.mkdir(parents=True, exist_ok=True)
    output_manifest_path = Path(output_manifest).expanduser().resolve()

    predictor = nnUNetPredictor(
        device=torch.device(device),
        perform_everything_on_gpu=device == "cuda",
        verbose=False,
        verbose_preprocessing=False,
        allow_tqdm=True,
    )
    predictor.initialize_from_trained_model_folder(
        model_training_output_dir=str(Path(model_training_output_dir).expanduser().resolve()),
        use_folds=(fold,),
        checkpoint_name=checkpoint_name,
    )

    network = predictor.network.to(torch.device(device))
    network.load_state_dict(predictor.list_of_parameters[0], strict=True)
    network.eval()

    patch_size = [int(x) for x in predictor.configuration_manager.patch_size]
    target_spacing_xyz = tuple(
        float(x) for x in reversed(predictor.configuration_manager.spacing)
    )
    window = intensity_window_hu or [-100.0, 240.0]
    crop_margin = margin_mm or [20.0, 20.0, 20.0]

    frame = pd.read_csv(manifest_path)
    rows: list[dict[str, Any]] = []
    for _, row in frame.iterrows():
        patient_id = str(row["patient_id"])
        image_path = resolve_phase_path(row, phase, "image")
        mask_path = resolve_phase_path(row, phase, "tumor_mask", fallback_columns=["tumor_mask"])
        if _is_missing(image_path) or _is_missing(mask_path):
            continue

        image = sitk.ReadImage(str(image_path), sitk.sitkFloat32)
        mask = sitk.ReadImage(str(mask_path))
        cropped_image, cropped_mask = _crop_image_and_mask(image, mask, crop_margin)
        resampled_image = _resample_image(cropped_image, target_spacing_xyz, is_label=False)
        resampled_mask = _resample_image(cropped_mask, target_spacing_xyz, is_label=True)

        image_array = clip_and_scale(sitk.GetArrayFromImage(resampled_image), window)
        mask_array = (sitk.GetArrayFromImage(resampled_mask) > 0).astype(np.float32)
        center = center_from_mask(mask_array) or default_center(image_array)
        image_patch = crop_centered(image_array, center=center, size=patch_size)
        mask_patch = crop_centered(mask_array, center=center, size=patch_size)

        with torch.inference_mode():
            image_tensor = torch.from_numpy(image_patch[None, None, ...]).to(torch.device(device))
            mask_tensor = torch.from_numpy(mask_patch[None, None, ...]).to(torch.device(device))
            feature_map = _extract_deepest_feature_map(network, image_tensor)
            pooled_mask = F.interpolate(mask_tensor, size=feature_map.shape[2:], mode="nearest")
            feature_vector = (
                _masked_average_pool(feature_map, pooled_mask)
                .squeeze(0)
                .detach()
                .cpu()
                .numpy()
                .astype(np.float32)
            )

        patient_dir = output_root / patient_id
        patient_dir.mkdir(parents=True, exist_ok=True)
        feature_path = patient_dir / f"{phase}_encoder_features.npy"
        np.save(feature_path, feature_vector)
        rows.append(
            {
                "patient_id": patient_id,
                "phase": phase,
                "feature_path": str(feature_path),
                "feature_dim": int(feature_vector.shape[0]),
            }
        )

    result = pd.DataFrame(rows)
    output_manifest_path.parent.mkdir(parents=True, exist_ok=True)
    result.to_csv(output_manifest_path, index=False)
    return result


def attach_phase_encoder_features(
    manifest_path: str | Path,
    feature_manifest_path: str | Path,
    phase: str,
    output_manifest: str | Path,
) -> pd.DataFrame:
    base = pd.read_csv(manifest_path)
    features = pd.read_csv(feature_manifest_path)
    column_name = f"{phase}_encoder_features"
    subset = features.loc[:, ["patient_id", "feature_path"]].rename(columns={"feature_path": column_name})
    merged = base.merge(subset, on="patient_id", how="left")
    destination = Path(output_manifest).expanduser().resolve()
    destination.parent.mkdir(parents=True, exist_ok=True)
    merged.to_csv(destination, index=False)
    return merged
